version: '2'

services:
  pihole:
    container_name: pihole-vlan
    image: pihole/pihole:latest # check the latest version on docker hub.
    hostname: pihole # set an easy hostname to remember
    domainname: DOMAIN # your local domain name
    mac_address: de:ad:be:ef:ff:01 # can change or leave this
    cap_add:
      - NET_ADMIN
    networks:
      macvlan0: # same as network specified below
        ipv4_address: PIHOLE_IP # the IP of the pihole container
    dns:
      - 127.0.0.1 # use local DNS, since the pihole 
      - 1.1.1.1 # optional fallback DNS
    ports: # expose all pihole ports.
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    volumes: # mount our data volumes.
       - '/pihole/pihole/:/etc/pihole/'
       - '/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
    environment: # set variables for pihole configuration.
      ServerIP: PIHOLE_IP # must match ipv4_address above
      VIRTUAL_HOST: HOSTNAME.DOMAIN  # Must be hostname + domainname from above
      WEBPASSWORD: "PASSWORD"
      TZ: 'Europe/London' # pick your timezone
    restart: unless-stopped

networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: PIHOLE_IP/32
          gateway: 192.168.0.1
          ip_range: PIHOLE_IP/32